// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFRsVdZ6BashSF7QLGpiq2qGbjf_dW4Y4',
    appId: '1:818320655266:web:49e5862a73ea2850b328fb',
    messagingSenderId: '818320655266',
    projectId: 'amuze-a2601',
    authDomain: 'amuze-a2601.firebaseapp.com',
    storageBucket: 'amuze-a2601.appspot.com',
    measurementId: 'G-6LKQEM14HJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgzEwI44yHapi6TGjgToe7plKIRZ6GpPw',
    appId: '1:818320655266:android:c33cbb2e5a83730ab328fb',
    messagingSenderId: '818320655266',
    projectId: 'amuze-a2601',
    storageBucket: 'amuze-a2601.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANf_oj3xrcTum8N3xQhY-WjDx2a1NVJKg',
    appId: '1:818320655266:ios:2cd432caf0dd587cb328fb',
    messagingSenderId: '818320655266',
    projectId: 'amuze-a2601',
    storageBucket: 'amuze-a2601.appspot.com',
    iosBundleId: 'com.example.amuze',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANf_oj3xrcTum8N3xQhY-WjDx2a1NVJKg',
    appId: '1:818320655266:ios:ece7910458c22f1db328fb',
    messagingSenderId: '818320655266',
    projectId: 'amuze-a2601',
    storageBucket: 'amuze-a2601.appspot.com',
    iosBundleId: 'com.example.amuze.RunnerTests',
  );
}
